version: '2'
services:
    web:
        build: .
        container_name: web_podcast
        ports:
            - "9596:5000"
        volumes:
            - ./app:/code
        depends_on:
            - redis
    redis:
        image: redis
        container_name: redis_podcast
